// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGSRrOX4B02x92aNorCDOkGuWofyyOJao',
    appId: '1:491951450183:web:bc6934ab7a26cfb6a5a962',
    messagingSenderId: '491951450183',
    projectId: 'fir-all-b90fc',
    authDomain: 'fir-all-b90fc.firebaseapp.com',
    databaseURL: 'https://fir-all-b90fc-default-rtdb.firebaseio.com',
    storageBucket: 'fir-all-b90fc.appspot.com',
    measurementId: 'G-5G8PWFYGLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWbv7bd6azNEj4maBcMcTn35bYntyDr90',
    appId: '1:491951450183:android:d882a57dca4a194fa5a962',
    messagingSenderId: '491951450183',
    projectId: 'fir-all-b90fc',
    databaseURL: 'https://fir-all-b90fc-default-rtdb.firebaseio.com',
    storageBucket: 'fir-all-b90fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHP57J8oNmRtAqMP-1F2sQgvCfpKsg8ic',
    appId: '1:491951450183:ios:f5419b89a15cadd6a5a962',
    messagingSenderId: '491951450183',
    projectId: 'fir-all-b90fc',
    databaseURL: 'https://fir-all-b90fc-default-rtdb.firebaseio.com',
    storageBucket: 'fir-all-b90fc.appspot.com',
    iosBundleId: 'com.example.birabaseUi',
  );
}
